### ISSUE TITLE
Add Steam-Play-None compatibility tool

### ISSUE THREAD

**Issue by puddydoo** [DavidoTek/ProtonUp-Qt#152]
Make [Steam-Play-None](https://github.com/Scrumplex/Steam-Play-None) installable from ProtonUp-Qt

**Comment by DavidoTek** [comment]
That should be easily doable.

Just wondering, are there any other examples of games than `CrossCode` that benefit from `Steam-Play-None`?

**Comment by puddydoo** [comment]
Apparently it helps with modded slay the spire where mod the spire has black screen issues on proton and the game crashes on steam linux runtime

**Comment by sonic2kk** [comment]
There is no release for this tool, but the repository from `git` can simply be cloned and moved to `compatibilitytools.d`. A concern here could be file size / excess files, since it'll have the `.git` and potentially `.github` file.

Also, to my understanding, this is really only useful on Steam Deck where there is unfortunately no easy way to do what this compatibility tool does. On Linux Desktop, you can simply run your game's Linux port as-is. It might be worth noting that this is mainly useful on Steam Deck in the compatibility tool description.

**Comment by DavidoTek** [comment]
> There is no release for this tool [...] the .git and potentially .github file.

We can download the repo as a tar.gz, that should not include the .git file. Not sure if it's best to download the `main` branch as we cannot go back this way but on the other hand I don't think there is much that will change.

https://github.com/Scrumplex/Steam-Play-None/archive/refs/heads/main.tar.gz

> mainly useful on Steam Deck

We can add it to the description. Maybe this should only be available in `advanced mode`.
