### ISSUE TITLE
vkd3d is very outdated 

### ISSUE THREAD

**Issue by LethalManBoob** [DavidoTek/ProtonUp-Qt#169]
https://github.com/HansKristian-Work/vkd3d-proton/releases
it is currently 2 releases behind on protonup-qt

**Comment by DavidoTek** [comment]
Thanks for reporting the issue.

You have probably tried to install [vkd3d-lutris](https://github.com/lutris/vkd3d) which is a fork of HansKristian-Work's vkd3d and is two versions behind (2.6 instead of 2.8 as of now).

There should be a compatibility tool `vkd3d-proton` available which has then newest release from HansKristian's vkd3d.

I've found an issue with the Flatpak version of ProtonUp-Qt where it won't show `vkd3d-proton` due to a missing dependency (zstandard pip).
I will fix that soon.

**Comment by DavidoTek** [comment]
Fixed with https://github.com/flathub/net.davidotek.pupgui2/pull/10. Option `vkd3d-proton` is now displayed.

Update should be available in a few hours. Feel free to report whether everything works fine then @LethalManBoob
