### ISSUE TITLE
Show a message box when a compatibility tool failed to load

### ISSUE THREAD

**Issue by teppyboy** [DavidoTek/ProtonUp-Qt#184]
**Is your feature request related to a problem? Please describe.**
Without reading the log, I didn't notice that there were some CTs failed to load.

**Describe the solution you'd like**
Show a message box about CTs failed to load, and optionally the reason too

**Describe alternatives you've considered**
Read the logs, but since ProtonUp-Qt is designed for user-friendly experience I don't think we need to read the log for that thing.

**Comment by DavidoTek** [comment]
Having a way to inform the user if something really really goes wrong can make sense. 
I'm not sure whether it should/can also contain the error message to the dialog. Maybe a expandable section which contains the precise error and a text `Please report a bug on GitHub <url>`.

> because of missing 'zstandard' dependency

In the first place we should focus on resolving this kind of issues. Getting an issue due to a missing dependency (or missing internet connection, etc.) could confuse many users.

Maybe it would be better if the error dialog first will be displayed when the user actually tries to select/install the broken compatibility tool as ([currently at least](https://github.com/DavidoTek/ProtonUp-Qt/issues/162#issuecomment-1416431314)) the ctmod is only used for installing and not for detecting/removing compatibility tools. Though I'm open on this.

> in [my fork](https://github.com/teppyboy/ProtonUp-Qt/commit/43bfd37aa61d162e9c8c2a2c944d2092bec5bc58)

Fell free to open a PR :)

**Comment by teppyboy** [comment]
> Maybe it would be better if the error dialog first will be displayed when the user actually tries to select/install the broken compatibility tool

The current implementation doesn't show the CT when it failed to load, maybe we can show all the CTs in the dropdown and only load them if the user click on them

> Fell free to open a PR :)

Done :smile:, also implemented the detailed section (which is hidden by default) show the precise error.
![image](https://user-images.githubusercontent.com/42248228/218119282-ddbbe3c6-05bd-408b-be92-0406055f1e51.png)

**Comment by sonic2kk** [comment]
Looks really nice! Though I am interested in how this error got through in the first place.

Flatpak *should* manage all necessary dependencies, not sure about AppImage but I would guess so too right? It should have all the Python libs. Though this would be useful in cases like #169, where Flatpak was missing the Zstandard library (though cases like this should be few and far between).

So this would impact running from source, where there could be an instance that a new dependency is added to the `requirements.txt` but the installed dependencies are not. The requirements.txt [does have zstandard](https://github.com/DavidoTek/ProtonUp-Qt/blob/main/requirements.txt#L8), so nothing should be missing there.

<hr>

Regardless of this *specific* instance, it is good in general to show this dialog. Ctmods failing to load should really never happen but even for developing it would be handy to have :+1:

**Comment by teppyboy** [comment]
> Though I am interested in how this error got through in the first place.

I installed it from 3rd party Arch repos (chaotic-aur) so lol, my fault

**Comment by DavidoTek** [comment]
Same here, looks very good!

> The current implementation doesn't show the CT when it failed to load, maybe we can show all the CTs in the dropdown and only load them if the user click on them

Interesting idea, we should keep it in mind. The name of the ctmod should be available in `CT_NAME` without having to load the whole module.

> I installed it from 3rd party Arch repos (chaotic-aur)

Maybe someone can create an issue here: https://github.com/chaotic-aur/packages/issues
