### ISSUE TITLE
Expand Proton-tkg downloads to include Wine-tkg

### ISSUE THREAD

**Issue by KenJyn76** [DavidoTek/ProtonUp-Qt#232]
Hi!

Currently, ProtonUp-Qt can download Proton-tkg and Proton-tkg (Wine master) to the Steam compat.d, I was wondering if this could be expanded to allow Wine-tkg to be downloaded for Lutris, Heroic, etc. It's the same CI system, so hopefully it wouldn't be too huge a hassle to include. 

Thanks!

**Comment by sonic2kk** [comment]
This is already supported for Lutris. It's not supported for Heroic but should be just a one-line change.

![image](https://user-images.githubusercontent.com/7917345/234731901-868039bc-5ee0-494f-af69-698e2253aa4c.png)

**Comment by sonic2kk** [comment]
#233 is up to implement Wine-tkg and Proton-tkg sources for Heroic.

**Comment by sonic2kk** [comment]
This feature should now be available as of c5d44efa331c478d0a0c93d9b281886e667935b5.

In my playing around with downloading Tkg builds with ProtonUp-Qt (unrelated to this feature request) I noticed a couple of issues that I'm troubleshooting and looking to fix. Namely:
- Too many failed CI builds will result in a Tkg build not showing any CI releases (reported in #236, this problem should be mostly mitigated with #237, but cannot be fully resolved as too many failed CI builds is a problem afaik no software could account for fully)
- The logic to remove existing Tkg builds is wrong (the `install_dir` appears to be generated wrong) and can result in Tkg builds being removed if multiple are installed as ProtonUp-Qt thinks they're duplicates and removes them
    - Conversely, this means installing a duplicate Tkg build may not be properly detected and could result in Unforeseen Consequences

**Comment by sonic2kk** [comment]
I think this is fully resolved now. The issues from above were resolved a while back:
- Proton-tkg and Wine-tkg were added for Heroic in #233.
- Failed CI builds issue was fixed with #237.
- Removal logic was fixed in #238, and the logic for extracting Tkg builds was refactored extensively in #250 to be cleaner in general.

I don't think there's any outstanding work left on this issue, particularly now that it should be available in a release now :-)
