### ISSUE TITLE
Game names gone

### ISSUE THREAD

**Issue by crlmahlberg** [DavidoTek/ProtonUp-Qt#24]
Thanks for this useful tool. When I first installed and used it, the names of the games that use a specific compatibility tool were displayed correctly (e.g., _Tom Clancy's Ghost Recon® Wildlands_), but all of a sudden it just says "None". Any idea what's going on and how that can be resolved?
![Bildschirmfoto vom 2021-12-22 02-40-29](https://user-images.githubusercontent.com/54212019/147026535-ecd282f2-2d26-4241-929e-14a071bc98eb.png)
PS: I searched all across Google but with no success, maybe you know the answer: I have more than a hundred games that use the same version of Proton GE. Is there a way to **batch update** them to another version, or do I have to change them, in Steam itself, one by one? Thanks a lot!

**Comment by crlmahlberg** [comment]
I managed to temporarily fix the main issue by deleting the file `/home/[username]/.config/pupgui/steam_applist.json`, which contained only three blank entries. The file was then recreated by ProtonUp-Qt and contains all game titles now, and the correct ones are displayed in the app.

**Comment by DavidoTek** [comment]
Seems like the download failed for some reason, maybe ProtonUp-Qt could check if the download was successful, will have to see how that could be done. You can force a "redownload" of the file by clicking the Update button in the about dialog.  

ProtonUp-Qt isn't capable of batch updating them to another version at the moment (you can do it using a text editor though by editing `<steam root>/config/config.vdf` and replacing occurrences of the old version).

@DavidoTek ToDo:
- Check if the steam applist download was successful, otherwise download again (try 3 times)
- Add an option to "batch update" all games from one Proton version to another

**Comment by crlmahlberg** [comment]
Thanks for the reply. The "batch update" option would be truly awesome and make your app indispensable for me and the way I use Steam! Looking forward to the enhancement!

**Comment by crlmahlberg** [comment]
Great, thanks for the update!
