### ISSUE TITLE
Add dxvk-gplasync as a compatibility tool

### ISSUE THREAD

**Issue by NaiveInvestigator** [DavidoTek/ProtonUp-Qt#243]
**Describe the solution you'd like**
To add this project [`dxvk-gplasync`](https://gitlab.com/Ph42oN/dxvk-gplasync) as an compatibility tool option. 

It is an dxvk async fork which increases performance well beyond what the 2.0 version does and brings a signficant boost in performance on low end PCs. Way more than the async dxvk 2.0. Well atleast on my machine lol.

I hope you consider this feature request! 

Also not related to this request lol but TYSM protonup-qt!! It helped a lot and was one of the main factors for me to try switching to linux full time.

**Comment by sonic2kk** [comment]
There is no existing logic that can fetch from GitLab, so it would take a bit of extra effort to implement, but it should be feasible to add this for Lutris. Once we figure out DXVK etc for Heroic it would also be possible for them.

It is probably possible to use this tool with Proton but it would involve modifying Proton builds' `lib`s and their prefixes, so that part is probably out-of-scope. It would be possible to add for Lutris though provided it has the same folder structure as DXVK (which I assume it would).

The main issue I see here is that the repository doesn't appear to distribute "packages" but rather stories archives on the repo itself, which is an unusual way of going about things. This would probably need to be a separate ctmod and wouldn't be easily derived from an existing one since it uses GitLab and uses VCS for storing the packages, so we'd need to clone the entire repo and extract the selected version, which brings me to the next problem: How to go about fetching the versions as well as then selecting them. Maybe this is something to report upstream first, to ask them to use packages, and then we'd investigate using a GitLab API to fetch the releases that way.

Side note: I thought GPL was just an option that was enabled for RADV (and that it was on by default with Mess 23.1) but I'm not a graphics expert, so it's very possible I'm wrong here :-)

**Comment by sonic2kk** [comment]
As an aside, I am wondering what the likelihood of this being "upstreamed" into dxvkasync is. The same argument could be made and has been made for D8VK being merged upstream into DXVK, and we still include that.

**Comment by sonic2kk** [comment]
I wanted to take a look at this a while back, but work+other projects got on top of me a little bit.

Might take a look at it later this week if I can spare some time, the main thing is as mention allowing downloads from both GitHub and GitLab, since they are two different APIs. The extraction and general makeup of the ctmod should be similar, it just has to download from GitLab using that API.

A while ago I also looked a bit into creating some kind of base ctmod class, I think I ran into a couple of issues basically with the best way to break things apart. In my head I probably wanted to do that first, since then downloading would be more generic, but that all can probably wait as it would be a pretty big rework probably across at least a couple of PRs.

I'd still like to look at it as the work I've been doing on other projects has subsided and my personal life has settle down a little bit, so if no one else is doing it I can make an attempt sometime this week unless someone is already doing so :-) I'll update if I don't get time or get anywhere.

<hr>

To update on my comment from earlier, D8VK is actually in the process of being upstreamed, but it still has a bunch of review to go through by the looks of it. However I don't think there is any plans from either DXVK/Valve or the author of this DXVK fork to do any upstreaming work (hosting on GitLab as well would also make this a little more difficult).

**Comment by NaiveInvestigator** [comment]
@Ph42oN

**Comment by Ph42oN** [comment]
I think upstreaming of async was chosen to not happen by DXVK dev pretty long ago. It looks like most people think async is not needed anymore because of Graphics Pipeline Library. That seems to be true in most games but there are situations with more stutter than async. It made me think why not both, and thats why gplasync was created.

I think getting this to upstream DXVK is very unlikely.

Getting this patch to GE-proton is possibility, but i am in GE discord server and people don't seem to care about this.

**Comment by sonic2kk** [comment]
I'm taking a look at implementing this, hoping to get a draft PR up soon :-)

**Comment by sonic2kk** [comment]
PR is up at #302, it wasn't nearly as infeasible of a refactor as I thought, but it also wasn't trivial and may still change based on PR feedback :-) Feel free to take a look at the code if you'd like!
