### ISSUE TITLE
Deleted-corrupted userdata/0/config/shortcuts.vdf makes shortcut names appear as blank

### ISSUE THREAD

**Issue by redirectto** [DavidoTek/ProtonUp-Qt#278]
**Describe the bug**  
ProtonUp-Qt gamelist showed a lot of shortcuts I had already removed from steam.
After some tweaking it only shows steam games names, non-steam games appear as blank.

**To Reproduce**  
1. I modified /home/deck/.local/share/Steam/userdata/0/config/shortcuts.vdf to remove the unnecessary shortcuts
2. I probably did it wrong and did not make any backup of the original file.
3. Either modify shortcuts.vdf to a corrupted state or delete the file.
4. Check game list.

6ex. I tried to copy the same file from userdata/<userid>/config but it doesn't work
7ex. I also tried recreating the file from scratch but I don't know how to do that properly.

**Expected behavior**  
I expected to fix the first issue by removing the unnecessary games since steam and other apps load the shortcuts from /home/deck/.local/share/Steam/userdata/<userid>/config/shortcuts.vdf but now the games either don't appear or have blank names.

**Screenshots**  
https://i.imgur.com/L6IF1ZD.png

**Desktop (please complete the following information):**  
 - **Platform**: Steam Deck
 - **System**: SteamOS 3.4.8
 - **Version**: ProtonUp-Qt 2.8.1
 - **How did you install ProtonUp-Qt?**: Discover app store

**Terminal output**  
This output appear in an infinite loop
```
QCoreApplication::postEvent: Unexpected null receiver
```

**Comment by sonic2kk** [comment]
It looks like the image you posted is unavailable. You can attach screenshots directly to GitHub posts though :-)

> I modified `/home/deck/.local/share/Steam/userdata/0/config/shortcuts.vdf` to remove the unnecessary shortcuts

Note that this is a binary VDF format and is different to other VDF files such as `config.vdf`, which is essentially a plain-text format. I'm not sure how you edited it (doing it in a text editor will probably lead to corruption), but if you used a hex editor/maybe some VDF parser that can modify the file, that's no worries.

For your own future endeavours, it is probably best to remove shortcuts by either deleting the shortcuts from Steam by hand, or by deleting the `shortcuts.vdf` file (the nuclear option :sweat_smile:). For manual deletion, there is a category for shortcuts, and you can also select and remove multiple entries from Desktop Mode on Steam Deck/Steam Big Picture.

> After some tweaking it only shows steam games names, non-steam games appear as blank.

So this is the core of the problem if I'm understanding. You modified the `shortcuts.vdf` file, and now the shortcuts are showing up blank.

This is probably a result of the VDF file being corrupted and the VDF library is unable to read the file names correctly. Probably the best approach is to hide loaded shortcuts whose names are blank.

> I expected to fix the first issue by removing the unnecessary games since steam and other apps load the shortcuts from /home/deck/.local/share/Steam/userdata//config/shortcuts.vdf but now the games either don't appear or have blank names.

This is also where ProtonUp-Qt loads the shortcuts from, and it uses a library to parse the file. Since the file has been manually edited, I think it is fair to discard entries that can't be read properly (i.e. with a blank name).

<hr>

The action item here for ProtonUp-Qt is to perhaps not parse Steam apps in general whose names are blank (`not len(SteamApp.app_name.strip)` perhaps?).

**Comment by redirectto** [comment]
I don't know why but imgur seems not to work properly.
Here is the screenshot.
![L6IF1ZD](https://github.com/DavidoTek/ProtonUp-Qt/assets/60912584/b9b64a40-ee51-4f6f-9572-d385f12885be)
So I guess I should remove both shortcuts.vdf files and create every single shortcut from scratch that way proton up qt will detect the games properly, that will hurt since I will also need to delete and recreate shadercaches and compatdata.
If I want to edit the vdf files, I should use a hex editor or a text editor such as notepad++ but being careful with the special characters.

**Comment by DavidoTek** [comment]
> So I guess I should remove both shortcuts.vdf [...] that will hurt [...]

I guess It should be possible to fix the corrupted file, but that's quite a complex task.

> I should use a hex editor or a text editor such as notepad++ 

I'm working on something if you want to edit the shortcuts in the future. I hope I'll get this finished soon ;)

![grafik](https://github.com/DavidoTek/ProtonUp-Qt/assets/54072917/91922007-a007-45cc-8574-096f0c536682)

**Comment by redirectto** [comment]
I just deleted both shortcuts.vdf files and re added an app (citra emulator) but it still shows no name inside Protonupqt.
![Screenshot_20230819_153857](https://github.com/DavidoTek/ProtonUp-Qt/assets/60912584/f7cda9d3-e924-4e97-bd7d-8f7c45d45165)
Maybe it has something to do with /home/deck/.local/share/Steam/config/config.vdf

**Comment by sonic2kk** [comment]
May be related to #275, which should be included in ProtonUp-Qt 2.8.2 (#276). This is not available as a Flatpak just yet (flathub/net.davidotek.pupgui2#21).

**Comment by sonic2kk** [comment]
ProtonUp-Qt v2.8.2 was released as Flatpak and should be available from Flathub shortly.

@redirectto Once ProtonUp-Qt v2.8.2 is available to you, please re-test and see if your issue is resolved. Fingers crossed!

**Comment by redirectto** [comment]
Hooray! now it's fixed and works as intended 
![Screenshot_20230820_005744](https://github.com/DavidoTek/ProtonUp-Qt/assets/60912584/f992bfb2-bfaa-4fae-a7c1-3d652d584d4d)
Thank you guys
