### ISSUE TITLE
rather quiter hilarious texture artifacting but only on certain objects in starfield

### ISSUE THREAD

**Issue by bluedinosaur139** [DavidoTek/ProtonUp-Qt#291]
Please fill out following when reporting a new bug:

**Describe the bug**  
this only seems to effect proton ge 8-16 and only in starfield ofc because its bethesda
sometimes quest npc are hiliariously patchy bald like they got into a fight with a weed whacker and lost.
other times i saw the marshall of the rangers turn pitch black on his face but only when close like conversation close, as soon as you move a few feet away the regular texture fades back in, and somewhere inbetween he looks like a burnt hotdog, this is just funny asf but if you can be bothered to fix that crappy game please do !!!!

**To Reproduce**  
1. Manjaro linux with 7800x3d asus b650 tuf gaming wifi 32 gb 6400 oc ram and a 6900 xt, with a 4 tb gen 4 nvme
2.it takes this god tier rig to get a stable 60 fps and some cities like akila are more like 40 lmao this is on ultra at 2k no upscaling or vrs or vsynch, VRR is ON!!!!!
3. i used proton up qt to get this ge 8-16 version then enabled it by default in steam compatibility
4. Starfield is the only game with this issue and is the main reason i use ge proton versions, keep up god's work bruddah!
5. main issue is just some textures failing to load on npc, there is also the odd green flash of light from reflections too but not sure if thats on amd or proton or bethesda lol 

**Expected behavior**  
Perfect frames with no texture load in issues, it does go away if i switch to proton experimental, once again its only this starfield, the worst optimized pc game in history with the issue, cant stress that enough

**Desktop (please complete the following information):**  
 - **Platform**:Manjaro linux, kde desktop, steam, PC
 - **System**: Manjaro  x 86 - 64 bit
 - **Version**: ge proton 8-16
 - **How did you install ProtonUp-Qt?**: using manjaro app store with aur support enabled, v 2.8.2
**Additional context**  
it made me laugh hard as hell both times and i thanked god for a hilarious bug, but nevertheless i thought i would let you know

**Terminal output**  
```
Open the Terminal app and type one of the following commands and press Enter (The app is called "Konsole" on Steam Deck):

If you installed ProtonUp-Qt via Flatpak (Discover on Steam Deck), type:
flatpak run net.davidotek.pupgui2

If you have downloaded the AppImage, navigate to the folder containing the AppImage file and type:
./ProtonUp-Qt*.AppImage

Try to replicate the bug and paste the text output of the command here afterwards.
```
Loading locale en / en_US
Loaded ctmod GE-Proton
Loaded ctmod Wine-GE
Loaded ctmod Boxtron
Loaded ctmod D8VK (nightly)
Loaded ctmod Kron4ek Wine-Builds Vanilla
Loaded ctmod Lutris-Wine
Loaded ctmod Luxtorpeda
Loaded ctmod NorthStar Proton (TitanFall 2)
Loaded ctmod Proton Tkg
Loaded ctmod Proton Tkg (Wine Master)
Loaded ctmod Roberta
Loaded ctmod Steam-Play-None
Loaded ctmod SteamTinkerLaunch
Loaded ctmod SteamTinkerLaunch-git
Loaded ctmod vkd3d-lutris
Loaded ctmod vkd3d-proton
Loaded ctmod Wine Tkg (Valve Wine)
Loaded ctmod Wine Tkg (Vanilla Wine)
Loaded ctmod DXVK
Loaded ctmod DXVK Async
Loaded ctmod DXVK (nightly)

**Comment by sonic2kk** [comment]
Maybe there's some misunderstanding, but this project isn't responsible for creating Proton versions. GE-Proton is not created here, nor are any other versions of Proton. This tool, ProtonUp-Qt, only facilitates downloading the tools, but they aren't developed here, so bugs like this can't be resolved here :-) ProtonUp-Qt is not responsible in any way for developing any version of Proton or other tool that it can download.

If you're looking to report this bug upstream, probably the best place would be [vkd3d-proton](https://github.com/HansKristian-Work/vkd3d-proton/), the translation layer responsible for converting D3D12 calls to Vulkan. However please check first to see if this is already known or fixed in a newer git release, keeping in mind that especially for Starfield, Mesa-git (not Mesa 23.2.1, maybe Mesa 23.2.2) has a number of performance and bug fixes for Starfield. If this is not fixed and you have confirmed the latest of both your GPU driver and vkd3d-proton version don't fix the problem, report that also, and you may also be advised to report it upstream to Mesa.

Hopefully you can resolve your issue though, but it can't be resolved here.

**Comment by bluedinosaur139** [comment]
lmao, im high, thank you, this lemonade herb i tell ya man, i will report it there
