### ISSUE TITLE
[Add/Updated] DXVK ASYNC replace or insert the for dxvk-gplasync

### ISSUE THREAD

**Issue by Milor123** [DavidoTek/ProtonUp-Qt#292]
Add new DXVK ASYNC, because the ASYNC version in the proton-QT is unmantained

[https://gitlab.com/Ph42oN/dxvk-gplasync](https://gitlab.com/Ph42oN/dxvk-gplasync)

Or how can i add it to my proton-QT?
Thank you very much guys !!! Greetings!

**Comment by DavidoTek** [comment]
Thanks for reporting that.

> the ASYNC version in the proton-QT is unmantained

I see.
It is also linked here and it seems there are quite a few people using this https://github.com/Sporif/dxvk-async/issues/64#issuecomment-1441560713

---

> Or how can i add it to my proton-QT?

All of ProtonUp-Qt's supported compatibility tools are currently hosted on GitHub. For dxvk-gplasync, you would need to create/modify a compatibility tool to download the releases (tar.gz) from GitLab.

Have a look at the implementation for the vanilla dxvk which is fetched from GitHub. It is implemented in Python: https://github.com/DavidoTek/ProtonUp-Qt/blob/main/pupgui2/resources/ctmods/ctmod_z0dxvk.py

What you need to do is following:
- Create a new file for the compatibility tool module (ctmod), e.g. `ctmod_z3dxvkgplasync.py` and copy the necessary code from the existing ctmod
- Modify `fetch_releases` to return a list of available versions which are available on GitLab: `v2.3-1`, `v2.2-4`, ...
- Modify `get_tool` and `__download` to download the compatibility tool into the correct folder
- `__fetch_github_data` can probably be removed / modified to work with GitLab

It seems like Ph42oN is providing releases and also adds the builds as tar.gz to the repo. Interesting:
- https://gitlab.com/Ph42oN/dxvk-gplasync/-/releases - we should prefer this method
- https://gitlab.com/Ph42oN/dxvk-gplasync/-/tree/main/releases

Feel free to give it a try and get in touch if you have any questions.
When your ctmod code works, you can create a Pull Requests so it can be added to the official ProtonUp-Qt releases.

---

There already is another issue on adding dxvk-gplasync, but there hasn't been much progress since then.

I will close this issue as it is a duplicate, the discussion can be continued in the existing issue: https://github.com/DavidoTek/ProtonUp-Qt/issues/243

**Comment by Milor123** [comment]
I am not developer bro i dont know about of do the pull request. Sorry i cant help. I would like do it.
Thank u very much bro !!!
