### ISSUE TITLE
Protonup-qt broke on qt6

### ISSUE THREAD

**Issue by robzombie91** [DavidoTek/ProtonUp-Qt#349]
Please fill out following when reporting a new bug:

**Describe the bug**  
Protonup-qt will not launch on qt-6 based desktops like the newer plasma 5.90.2 aka plasma 6

**To Reproduce**  
Install plasma 6 rc
install protonup-qt
try to launch protonup-qt

**Expected behavior**  
It should launch the protonup-qt window

**Screenshots** 
N/A

**Desktop (please complete the following information):**  
 - **Platform**: PC
 - **System**: Arch Linux w Plasma 6.0 RC1 on Zen Kernel 6.7.2 
 - **Version**: ProtonUp-Qt 2.9.1-1
 - **How did you install ProtonUp-Qt?**: Via the AUR (arch user repository)

**Additional context**  
None

**Terminal output**  
```
[rob@robpc ~]$ protonup-qt
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3.11/site-packages/pupgui2/__main__.py", line 1, in <module>
    from pupgui2.pupgui2 import main
  File "/usr/lib/python3.11/site-packages/pupgui2/pupgui2.py", line 10, in <module>
    from PySide6.QtGui import QIcon, QKeyEvent, QKeySequence, QShortcut
ImportError: /usr/lib/python3.11/site-packages/PySide6/QtGui.abi3.so: undefined symbol: _ZN5QFont11tagToStringEj, version Qt_6

```

**Comment by sonic2kk** [comment]
Sounds like an issue with PySide6 / the PySide 6 version rather than ProtonUp-Qt.

Does this happen with the Flatpak or AppImage version out of interest?

**Comment by sonic2kk** [comment]
Found a similar issue for PySide6 reported a while ago for someone on Kubuntu: https://bugreports.qt.io/browse/PYSIDE-1950. They were getting `ImportError: env/lib/python3.8/site-packages/PySide6/QtCore.abi3.so: undefined symbol: _ZNK20QFutureInterfaceBase15isChainCanceledEv, version Qt_6`. Not the same error but similar enough that they might be related.

**Comment by DavidoTek** [comment]
The issue is normally caused by a mismatch of the ABI versions of the PySide6 version and Qt version.

You can run `python3 -c "import PySide6; print(PySide6.__version__)"` to get your PySidie6 version. Compare it to the installed Qt version (check the installed packets or run some Qt utility like qtdiag6 to get the version: `qtdiag6 | grep Qt`)

> Does this happen with the Flatpak or AppImage version out of interest

Should not happen here as the ABI versions are matched.

> It might also be a good idea to mention this on the AUR package repo (protonup-qt), as the AUR package is managed by another person and they may have more insights too
> Perhaps uninstalling and re-installing PySide6 could help your issue?

Yes, that is the place to report it. It is maintained separately from the official AppImage and Flatpak releases.

Although, this issue sounds more like a configuration issue with Arch, or a missing update. Try updating your OS.

> protonup-qt-bin

This one is using the AppImage version in the background. But as you pointed out, is still back on v2.8.2

**Comment by robzombie91** [comment]
The flatpak version doesn't have this issue
