### ISSUE TITLE
Buttons don't fit on window

### ISSUE THREAD

**Issue by ozon85** [DavidoTek/ProtonUp-Qt#360]
Hello.
**I have a problem:**
It is not possible to resize the window, and the buttons do not fit in the "Custom install Directory" window. And "Install Compatibillity Tool" too. I have an enlarged font.
![buttons](https://github.com/DavidoTek/ProtonUp-Qt/assets/79962382/f722472a-17ef-4d7c-8afa-ff09b6ba2ff7)

**Solution I'd like**
Make the window resizable or automatically adjusted to the required size

**Comment by sonic2kk** [comment]
I believe the core of this problem is ProtonUp-Qt's fixed window sizes, which came up at least once before (https://github.com/DavidoTek/ProtonUp-Qt/discussions/309#discussioncomment-7606883).

Moving away from fixed dialog sizes is probably the solution, but I'm not fluent enough in Qt to comment on how to do this.

I don't think simply making dialogs resizeable is the fix here, because right now widgets are not always positioned relative. For example making this dialog resizeable would have this problem (screenshot taken running from main @ 21e2b3fdde73298ca14bf89c42c08cd95d8a2cc1 with the `maximumSize` property reset the default from Qt Designer, `16777215x16777215`):

![image](https://github.com/DavidoTek/ProtonUp-Qt/assets/7917345/3cab642b-f87c-4688-ad4b-4114ab4c1b1b)

On a related note, sometimes windows have the opposite problem, but it is once again related to font sizes. For example, on my system with the ProtonUp-Qt Flatpak, some dialogs are slightly too big and buttons don't align properly to the bottom.

![image](https://github.com/DavidoTek/ProtonUp-Qt/assets/7917345/55bab1ec-7508-46fa-a971-dec23c73ef72)

So I think the overall fix is to move away from fixed with/height window sizes, which means we'd have to position things like buttons more "relatively" to the bottom of the window (which would fix the resizing issue in the first screenshot), and also ensure that windows are the correct size to display the widgets they're meant to.

<hr>

In terms of how to actually solve this, though, I don't have any real ideas :sweat_smile: This is just some additional context to the problem.

**Comment by sonic2kk** [comment]
I figured out from [this StackOverflow answer](https://stackoverflow.com/a/1151867/1952066) that, from Qt Designer, we can set the top-level layout for a dialog to have a `layoutSizeConstraint` of `SetFixedSize`. This means the layout will decide the size of the window, and the minimum/maximum size for the dialog is mostly ignored. I say mostly, because if the minimum and maximum size are still the same, Qt will still infer that the window should not be resizeable, but we can probably set this flag from code if we really want to remove the minimum/maximum size from the `.ui` file.

I tested this out on the Custom Install Directory dialog and it "works", in that, I set the dialog height to 1,000, and the height was correctly clamped to the minimum required size for the dialog. I didn't touch the width, however, as you can see, it's a little... off...

![image](https://github.com/DavidoTek/ProtonUp-Qt/assets/7917345/7170bffe-b0e1-4a14-8dfa-3dfab91903b6)

The width of the elements seems to shrink. This isn't a case of the dialog getting *wider*, if you compare with the earlier screenshots, you can see the width of the elements has *shrunk*.

I tried fiddling with the size policies of the form layout and nested horizontal layout in the dialog, as well as the widgets themselves, but didn't get anywhere.

Still, maybe this is a step in the right direction? Hopefully it's at least a bit of a hint :-)

**Comment by DavidoTek** [comment]
> I believe the core of this problem is ProtonUp-Qt's fixed window sizes, which came up at least once before (#309 (reply in thread)).

Yes

> So I think the overall fix is to move away from fixed with/height window sizes, which means we'd have to position things like buttons more "relatively" to the bottom of the window

Ideally, if all layouts were perfect, all windows can be resized to any size and it would still look good.
We need to fix the layouts for this and disable the fixed size.

> I figured out from this StackOverflow answer that, from Qt Designer, we can set the top-level layout for a dialog to have a layoutSizeConstraint of SetFixedSize. This means the layout will decide the size of the window, and the minimum/maximum size for the dialog is mostly ignored
> Still, maybe this is a step in the right direction? Hopefully it's at least a bit of a hint :-)

That seems to be the way to go. I guess we can still set a minimum size if it gets too small.

**Comment by sonic2kk** [comment]
If ProtonUp-Qt is using the KDE Breeze theme (currently only happens if using a systemwide PySide6, which the AUR packages may use), the KDE Breeze theme has a similar problem to this issue. In my case, it isn't as extreme as OP.

![image](https://github.com/DavidoTek/ProtonUp-Qt/assets/7917345/e34fa3d2-91f5-45a8-816f-30275c618bf0)

There is also an issue in the Games List dialog, where the window is a bit too small for the games list table, meaning it will show a scrollbar.

![image](https://github.com/DavidoTek/ProtonUp-Qt/assets/7917345/42238068-87f7-4ba5-b750-94eb85df1372)

As an aside, some other parts of the UI look a bit off with this Breeze theme, such as on the CtInfo dialog, the table widget in the stacked layout is missing a border that other table widgets have:

![image](https://github.com/DavidoTek/ProtonUp-Qt/assets/7917345/87965771-7dba-4428-ae57-fe341ab472ee)

<hr>

If there was a good way to set a minimum window size for dialogs that currently have fixed sizes based on their content (so that it occupies the minimum amount of space + potentially some padding that we can define), I think that would fix the problem in the OP. My experiments after my earlier comment didn't lead anywhere unfortunately.

**Comment by DavidoTek** [comment]
> If there was a good way to set a minimum window size for dialogs that currently have fixed sizes based on their content (so that it occupies the minimum amount of space + potentially some padding that we can define), I think that would fix the problem in the OP. My experiments after my earlier comment didn't lead anywhere unfortunately.

I guess we need to get rid of fixed sized dialogs at some point and make them resizable. Setting a minimum size should be possible in Qt Designer:

![grafik](https://github.com/DavidoTek/ProtonUp-Qt/assets/54072917/1acf1a76-a123-4146-852a-c6b6fc387645)

> I don't think simply making dialogs resizeable is the fix here, because right now widgets are not always positioned relative. For example making this dialog resizeable would have this problem (screenshot taken running from main @ 21e2b3f with the maximumSize property reset the default from Qt Designer, 16777215x16777215):

That can be fixed quite easily be setting a layout to the QDialog instead of adding one manually:

![grafik](https://github.com/DavidoTek/ProtonUp-Qt/assets/54072917/f4b7d98e-92ec-4055-9717-310ab2b6eda3)

![grafik](https://github.com/DavidoTek/ProtonUp-Qt/assets/54072917/87597146-b654-43ee-8c20-22d0c70b522c)

https://github.com/DavidoTek/ProtonUp-Qt/pull/396
