### ISSUE TITLE
Crashes Instantly

### ISSUE THREAD

**Issue by cafecitohippo** [DavidoTek/ProtonUp-Qt#393]
Please fill out following when reporting a new bug:

**Describe the bug**  
When starting ProtonUp-QT, the icon will appear in the window list and then crash before opening. It ran fine previously.

**To Reproduce**  
Launch the app.

**Expected behavior**  
The app to open up.

**Screenshots**  

**Desktop (please complete the following information):**  
 - **Platform**: Linux
 - **System**: EndeavourOS -- KDE 6.0 -- Wayland
 - **Version**: For example ProtonUp-Qt 2.5.0
 - **How did you install ProtonUp-Qt?**: Installed via AUR - 2.9.2-1

**Terminal output**  
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3.12/site-packages/pupgui2/__main__.py", line 1, in <module>
    from pupgui2.pupgui2 import main
  File "/usr/lib/python3.12/site-packages/pupgui2/pupgui2.py", line 16, in <module>
    from pupgui2 import ctloader
  File "/usr/lib/python3.12/site-packages/pupgui2/ctloader.py", line 9, in <module>
    from pupgui2.util import create_msgbox
  File "/usr/lib/python3.12/site-packages/pupgui2/util.py", line 26, in <module>
    from pupgui2.steamutil import remove_steamtinkerlaunch, is_valid_steam_install
  File "/usr/lib/python3.12/site-packages/pupgui2/steamutil.py", line 11, in <module>
    from steam.utils.appcache import parse_appinfo
ModuleNotFoundError: No module named 'steam'


If you installed ProtonUp-Qt via Flatpak (Discover on Steam Deck), type:
flatpak run net.davidotek.pupgui2

If you have downloaded the AppImage, navigate to the folder containing the AppImage file and type:
./ProtonUp-Qt*.AppImage

**Comment by sonic2kk** [comment]
AUR package issues should be reported to the AUR package maintainer. There are two so I am unsure which one you used.
- `protonup-qt`: https://aur.archlinux.org/packages/protonup-qt
    - I am going to guess it's this one, because the other one is out-of-date and only at 2.9.1, and you have reported 2.9,2
- `protonup-qt-bin`: https://aur.archlinux.org/packages/protonup-qt-bin

The issue you are facing is because of a missing Python package. People have had issues with other missing Python packages, some of the comments on that issue should help you already I think.

As noted in https://github.com/DavidoTek/ProtonUp-Qt/issues/349#issuecomment-1915319550, the AUR package is maintained separately and issues like this should be reported to those package maintainers.

**Comment by cafecitohippo** [comment]
Ah, didn't think to check the AUR comments. Thanks for the link. Did a clean build instead of just yay -R and reinstalling. Good to go now.
