### ISSUE TITLE
Does this work as an offline installer?

### ISSUE THREAD

**Issue by Darthagnon** [DavidoTek/ProtonUp-Qt#410]
Does ProtonUp-Qt work as an offline installer for Proton, Wine, etc.?

When I get a Steam Deck, I'm planning to install Windows on it purely because there are offline installers available for most software that will work without an internet connection to package managers' repos.

I wish Linux had the same philosophy, and was wondering whether this tool would install these dependencies without internet?

**Comment by DavidoTek** [comment]
No, ProtonUp-Qt downloads all compatibility tools from GitHub.
It wouldn't be possible to include all possible tools because they would use up several hundreds of gigabytes.

You can [download GE-Proton as an archive file](https://github.com/GloriousEggroll/proton-ge-custom/releases) without using ProtonUp-Qt from another computer and transfer it using a thumb drive in theory...

**Comment by sonic2kk** [comment]
Much software on Linux can be installed offline if not installed via a package manager; for example, AppImages.

ProtonUp-Qt *can* be used offline via the AppImage, but as mentioned it cannot install tools offline because they are fetched from external sources. Much functionality does work offline though, like the Shortcut Editor, Games List, Batch Update. It can still help you manage manually installed tools.

Regardless of operating system, tools that are a frontend for installing software from the web will always require an Internet Connection. It was recently (a matter of hours ago, #412) proposed to add functionality to extract a given archive into a compatibility tool folder using ProtonUp-Qt. Should such a proposal be eventually implemented, it could aid in offline usage.

**Comment by Darthagnon** [comment]
> No, ProtonUp-Qt downloads all compatibility tools from GitHub. It wouldn't be possible to include all possible tools because they would use up several hundreds of gigabytes.
> 
> You can [download GE-Proton as an archive file](https://github.com/GloriousEggroll/proton-ge-custom/releases) without using ProtonUp-Qt from another computer and transfer it using a thumb drive in theory...

GE-Proton is only 415mb? I'm not too sure where to manually extract it, but #415 would help a lot!

**Comment by sonic2kk** [comment]
One version of GE-Proton is only 415mb. Multiply that by all the releases, even just the last few. Plus, there's no way for ProtonUp-Qt to get the latest version unless it packaged a version with each release, which is unreasonable.

On top of this, ProtonUp-Qt also allows you to install other Proton versions. Even just the ones with Advanced Mode disabled, Proton-tkg stands out as another large one. There's also Kron4ek Wine builds, which there's reason why you might not want to use the latest so it's impossible to know which one should be downloaded without packaging several versions.

Expanding beyond Steam there's also Wine-GE which is of similar size, and Wine-tkg. Not to mention the variations thereof (builds from Wine Master can be up to 1gb!) and those are downloaded from CI, so there are several builds.

Even just packaging a few releases of each tool for each launcher we're already into tens of gigs.

**Comment by Darthagnon** [comment]
> One version of GE-Proton is only 415mb. Multiply that by all the releases, even just the last few. Plus, there's no way for ProtonUp-Qt to get the latest version unless it packaged a version with each release, which is unreasonable.

Do not include any releases with ProtonUp-Qt. Keep the current download function, but add a button for the user to select their own ZIPs of Proton, and it can install from ZIP. That's usually how such tools work on Windows (closest equivalent is probably ModOrganizer2 for Skyrim etc.)

**Comment by sonic2kk** [comment]
Package managers are intended to fetch packages and dependencies from repositories. That is *by design*. What you probably want is something that has all dependencies bundled together so that they don't have to be installed, something like an AppImage.

Also, you can still install your compatibility tools offline if you have the ZIPs. ProtonUp-Qt is a good way to do it if you want a shortcut, but the default is still extracting into the compatibility tool / runtime folder. No one is stopping you from doing this or making it difficult. The comparison to ModOrganizer 2 doesn't work here, because ModOrganizer 2 creates a virtual filesystem and other shenanigans in most cases including Skyrim.

Much Linux software does work offline and can do things offline. It happens that in your examples you're pointing to software designed with a network connection in mind. This would be like complaining that Steam requires an Internet Connection to install games, these are network-reliant tools that fetch things from the Internet. ProtonUp-Qt doesn't do anything that, provided you have the archives, you couldn't also do manually very quickly. The main benefit of ProtonUp-Qt imo (or similar tools) is that it can make *downloading* the archives easier, presenting the list of tools and versions. It's not like a package manager in the example you gave, which does a lot more legwork than ProtonUp-Qt.
