### ISSUE TITLE
Core dump when exiting the application

### ISSUE THREAD

**Issue by 1player** [DavidoTek/ProtonUp-Qt#42]
**Describe the bug**  

Every time I exit the application, python3.9 coredumps.

**To Reproduce**  
1. Open ProtonUp-Qt
2. Close it
3. Get notified by Fedora's ABRT that python3.9 crashed

**Desktop (please complete the following information):**  
 - OS: Fedora 35
 - Version: Flatpak

**systemd log**: see attachment.

[python3.9-backtrace.txt](https://github.com/DavidoTek/ProtonUp-Qt/files/8204635/python3.9-backtrace.txt)

**Comment by DavidoTek** [comment]
Can you run ProtonUp-Qt from Terminal and post the output here?

`flatpak run net.davidotek.pupgui2`

**Comment by 1player** [comment]
Well, I've seen the error a few times, and today I can't reproduce. I'll update the issue as soon as I manage to reproduce the problem.

**Comment by DavidoTek** [comment]
Do you have a gamepad connected?

There is a background thread for gamepad support that causes ProtonUp-Qt to crash when closed as the thread is not properly terminated. Only happens when a gamepad is connected.

**Comment by 1player** [comment]
Oh yes, that's it! Funnily enough, I wasn't able to reproduce because I did replace my gamepad's battery two days ago, and it was unplugged since. If I plug it in (it's a DS4), python crashes:

```
/app/bin/net.davidotek.pupgui2: line 3:     3 Aborted                 (core dumped) python3 /app/src/pupgui2/pupgui2.py --pupgui2-base-dir /app/share/pupgui2 "$@"
```

**Comment by sonic2kk** [comment]
Is this still an issue? I can't re-create anymore on Flatpak 2.7.7 or running from `main` (2a91c1d2f43fe4907324aa7472e53392d95ee9b1)

**Comment by DavidoTek** [comment]
Interesting. I did some testing and also wasn't able to replicate this anymore.
It might be fixed by a newer version of Python and/or PySide6 that ProtonUp-Qt is currently using.
If that is the case, we can close the issue.

**Comment by sonic2kk** [comment]
I noticed the OP issue notes Python 3.9. The Flatpak I believe uses 3.8, and my system uses 3.10.10. I don't have 3.9 to test but it is possible that something in 3.9 was causing the issue, though it may be more likely that a PySide6 version change fixed the problem. The `requirements.txt` specifies `PySide6-Essentials>=6.3.0`, and my system is using `6.3.1`.

I checked the history of the `requirements.txt` and noticed that on April 17th 2022, PySide6 was bumped from `6.2.4` to `6.3.0` (933191a). The last update on this issue was March 10th 2022, so it is possible that the PySide6 bump fixed this issue - I haven't rolled back to test, though :sweat_smile: 

Just as a little background on what may have fixed this issue.
