### ISSUE TITLE
[BUG] The newest ProtonUp QT AppImage 2.10.2  does link to 2.10.0 AppImage file

### ISSUE THREAD

**Issue by SoulInfernoDE** [DavidoTek/ProtonUp-Qt#440]
**Describe the bug**  
Not beeing able to download the latest appimage file

**To Reproduce**  

1. Go to 'davidotek website or github page and download the latest appimage file amd64'
2. You always get the version number 2.10.0

**Expected behavior**  
Download should give you the latest version number thats in the description of the download area

**Screenshots**  
![image](https://github.com/user-attachments/assets/86f8b6c7-6252-42ff-ad37-1405b85315aa)
https://github.com/DavidoTek/ProtonUp-Qt/releases/download/v2.10.2/ProtonUp-Qt-2.10.2-x86_64.AppImage
![image](https://github.com/user-attachments/assets/cdd6827b-5fbc-49fe-8971-58ae14a66bb9)

**Desktop (please complete the following information):**  
 - **Platform**: kernel 6.10.2
 - **System**: Linux Mint 22 Wilma
 - **Version**: ProtonUp-Qt 2.10.2
 - **How did you install ProtonUp-Qt?**: AppImage from Davidotek website or github release page

**Additional context**  
Starting the AppImage tells you don't have the latest version:
![image](https://github.com/user-attachments/assets/11d42e6b-0492-4e21-a3b9-d9d50003a152)

**Comment by sonic2kk** [comment]
This is probably because the tags are not synced with the release version.

When the v2.10.0 commit was pushed to bump the version, the AppImage didn't build if my understanding is correct. Some other commits were needed, and the tags seemed to have bumped for the releases on GitHub, but the actual ProtonUp-Qt version is going to be v2.10.0.

I think this can be fixed on the ProtonUp-Qt side by releasing a v2.10.3 "hotfix" that syncs the version in the codebase to be v2.10.3, the release tags to be v2.10.3, and then the AppImage commit can be v2.10.3.

**Comment by SoulInfernoDE** [comment]
Thanks so far, in the meantime you could change [the constants](https://github.com/DavidoTek/ProtonUp-Qt/blob/f2573d588a349fbdc77ccbe8fe720f41bf6a5305/pupgui2/constants.py#L9) to 2.10.2 to fix you dont have the latest version if you like. :heart:

**Comment by sonic2kk** [comment]
I'll let @DavidoTek decide how best to handle the versioning :-) I have no idea about release management.

**Comment by DavidoTek** [comment]
> When the v2.10.0 commit was pushed to bump the version, the AppImage didn't build if my understanding is correct. Some other commits were needed, and the tags seemed to have bumped for the releases on GitHub, but the actual ProtonUp-Qt version is going to be v2.10.0.

That is correct.
The actual version is v2.10.0. This one will also be released on Flathub https://github.com/flathub/net.davidotek.pupgui2/pull/30#issuecomment-2254282975
v2.10.2 only contains a patch to the CI to fix the AppImage build. I didn't bother updating the version in `constants.py`. Sorry for the confusion.

I will close this issue, will be fixed in the next released.
