### ISSUE TITLE
ProtonUp-Qt doesn't recognize Proton

### ISSUE THREAD

**Issue by mrmatteastwood** [DavidoTek/ProtonUp-Qt#71]
**Describe the bug**  
When launching the AppImage on Linux Mint 20.2 with Lutris and Steam + Proton installed, only Lutris is available from the "Install for:" dropdown.

**To Reproduce**  
1. Install Steam and Lutris on Linux Mint 20.2
2. Install a couple of Proton-enabled games for good measure
3. Download latest ProtonUp-Qt AppImage
4. Launch ProtonUp-Qt

**Expected behavior**  
Lutris and Proton should be available in the "Install for:" dropdown.

**Screenshots**  
https://paste.pics/H2K4L

**Desktop (please complete the following information):**  
 - OS: Linux Mint 20.2
 - ProtonUp-Qt 2.6.2 AppImage
 - My system config: https://termbin.com/pm2r

**Additional context**  
- Would love to reset ProtonUp-Qt's config to start with a clean slate, but cannot find its config files
- Tried manually adding Proton, but not sure what directory to choose

**Terminal output**  
```Gtk-Message: 19:50:07.191: Failed to load module "xapp-gtk3-module"
ProtonUp-Qt 2.6.2 by DavidoTek. Build Info: Official AppImage by DavidoTek.
Python 3.8.2 (default, Mar 13 2020, 10:14:16) [GCC 9.3.0], PySide 6.2.4
Platform: LinuxMint 20.2 Linux-5.13.0-27-generic-x86_64-with-glibc2.29
Loaded ctmod Proton-GE
Loaded ctmod Wine-GE
Loaded ctmod Boxtron
Loaded ctmod Kron4ek Wine-Builds Vanilla
Loaded ctmod Lutris-Wine
Loaded ctmod Luxtorpeda
Loaded ctmod Roberta
qt.pysideplugin: Environment variable PYSIDE_DESIGNER_PLUGINS is not set, bailing out.
qt.pysideplugin: No instance of QPyDesignerCustomWidgetCollection was found.
```

I'm probably doing or missing something completely n00by here. If so, any help would be appreciated.

**Comment by DavidoTek** [comment]
The location where Steam is installed looks quite strange. Normally it is installed in `/home/<your-username>/.steam/root`  
Just wondering, how did you come up with that path: `zzLocal/Appdata/Steam/` ?

The issue could be related to https://github.com/DavidoTek/ProtonUp-Qt/issues/63 which will be fixed in the next version of ProtonUp-Qt.
PS: The ProtonUp-Qt configuration is saved here: `/home/<your-username>/.config/pupgui/config.ini` (Only if you are using the AppImage file, otherwise the folder is different)

**Comment by DavidoTek** [comment]
Good. The correct path is `/home/<your-username>/.steam/root/compatibilitytools.d`  I missed the last part.

I've also uploaded the new version, that should fix the problem otherwise. Could you test that? https://github.com/DavidoTek/ProtonUp-Qt/releases/

(In case you're interested: The problem was that the **compatibilitytools.d** folder doesn't exists and ProtonUp-Qt didn't detect the Steam installation. The new version will detect that the folder is missing and should create it automatically)

**Comment by mrmatteastwood** [comment]
Yeah, I read through the other bug yesterday but didn't get to double-check. I took a look this morning and it's true, that folder was missing from my steam install! Then I came here to discover the new version. Perfect! Now everything works. Thank you kindly :-)
