### ISSUE TITLE
Drop down menus not working properly under Wayland

### ISSUE THREAD

**Issue by italoghost** [DavidoTek/ProtonUp-Qt#76]
**Describe the bug**  
Under Wayland, the drop down menus do not allow to scroll through the options. Under XWayland, this issue does not occur.

**To Reproduce**  
1. For example, go to 'Add version' and select the 'Proton-GE'.
2. Click on 'Version'
3. Try to scroll down to one of the versions. 
4. It won't be able to scroll through the options. 

**Expected behavior**  
It should be possible to scroll through the options.

**Desktop (please complete the following information):**  
 - OS: Arch Linux, GNOME 42 Wayland
 - Version: 2.6.4 from AUR.

**Comment by DavidoTek** [comment]
Confirmed, the issue only occurs on GNOME Wayland when using a source build. The drop down will close immediately.
The AppImage and [Flatpak](https://flathub.org/apps/details/net.davidotek.pupgui2) work fine, might be related to a different version of an included library, e.g. Qt (both use 6.2.4).

Can you check which Qt version you are using? (About > About Qt > first line)

**Comment by italoghost** [comment]
I am using the version 6.3.1!

**Comment by DavidoTek** [comment]
Okay, the issue seems to be related to PySide/Qt/GNOME. I may do some further investigation, but we'll probably need to wait for Qt/GNOME to fix the issue.

For now you can either use the Flatpak/AppImage or try to navigate the options using the keyboard (click on the box, then press up/down arrows, type version)
