### ISSUE TITLE
2.6.5 Does Not Launch on Steam Deck

### ISSUE THREAD

**Issue by rChen10** [DavidoTek/ProtonUp-Qt#80]
**Describe the bug**  
The UI does not show up when installed through the Discover store on Steam Deck.

**To Reproduce**  
1. Install version 2.6.5 through Discover.
2. Launch the application.

**Expected behavior**  
The UI for selecting Proton tools is displayed.

**Desktop (please complete the following information):**  
 - OS: Steam OS 3.2
 - Version ProtonUp-Qt 2.6.5 Flatpak

**Terminal output**  
```
ProtonUp-Qt 2.6.5 by DavidoTek. Build Info: DavidoTek Flathub build.
Python 3.9.9 (main, Nov 10 2011, 15:00:00) [GCC 11.3.0], PySide 6.3.1
Platform: Linux-5.13.0-valve15-1-neptune-02197-gf6ec7ad3762a-x86_64-with-glibc2.33
qt.qpa.xcb: could not connect to display  
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the applicat
ion may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhrdisplay, vnc, wayland-egl
, wayland, xcb.

/app/bin/net.davidotek.pupgui2: line 3:     3 Aborted                 (core dumped) python3 -m pupgui2 "$@"

```

**Comment by cprin21** [comment]
A bandaid 'workaround' is to use the 2.6.5 AppImage (go to where it is downloaded and make sure to open a terminal and put in 'sudo chmod +x ./ProtonUp-Qt-2.6.5-x86_64.AppImage' without the quotes.
Then you can run the AppImage.

**Comment by ziprasidone146939277** [comment]
Same here, after 2.6.5 upgrade:

`ProtonUp-Qt 2.6.5 by DavidoTek. Build Info: DavidoTek Flathub build.
Python 3.9.9 (main, Nov 10 2011, 15:00:00) [GCC 11.3.0], PySide 6.3.1
Platform: Linux-5.18.5-200.fc36.x86_64-x86_64-with-glibc2.33
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhrdisplay, vnc, wayland-egl, wayland, xcb.
`

Rollback works:

`sudo flatpak update --commit=adf3949a98c0220438d38d2853ce3ce33bbc26f28e123b0feb525f854a1b9686 net.davidotek.pupgui2
Looking for updates…

New net.davidotek.pupgui2 permissions:
    fallback-x11   x11
`

Thank You!

**Comment by nabel0** [comment]
Same problem here on my SteamDeck:

(deck@steamdeck ~)$ flatpak run net.davidotek.pupgui2
ProtonUp-Qt 2.6.5 by DavidoTek. Build Info: DavidoTek Flathub build.
Python 3.9.9 (main, Nov 10 2011, 15:00:00) [GCC 11.3.0], PySide 6.3.1
Platform: Linux-5.13.0-valve15-1-neptune-02197-gf6ec7ad3762a-x86_64-with-glibc2.33
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhrdisplay, vnc, wayland-egl, wayland, xcb.

/app/bin/net.davidotek.pupgui2: line 3:     3 Aborted                 (core dumped) python3 -m pupgui2 "$@"

**Comment by DavidoTek** [comment]
I've updated ProtonUp-Qt, should be available in a few hours.

For now, you can try launching ProtonUp-Qt from Terminal using `flatpak run --socket=x11 net.davidotek.pupgui2`

**Comment by Mitsunee** [comment]
> For now, you can try launching ProtonUp-Qt from Terminal using `flatpak run --socket=x11 net.davidotek.pupgui2`

just had the same issue on Fedora 36 (KDE/X11) and can confirm that this workaround fixed the issue for me 👍🏻

**Comment by ziprasidone146939277** [comment]
> I've updated ProtonUp-Qt, should be available in a few hours.

Working again. Thank You!

**Comment by nabel0** [comment]
Everything is working fine again....
