### ISSUE TITLE
No Titlebar on GNOME-Wayland

### ISSUE THREAD

**Issue by ulville** [DavidoTek/ProtonUp-Qt#98]
**Describe the bug**  
There is no titlebar/window decorations on any window of the application. I can still use "Hold super key and drag to move window" feature. 

**To Reproduce**  
1. Open the flatpak version of the app on a GNOME Wayland Session
2. See there is no titlebar

**Expected behavior**  
There should be a titlebar

**Screenshots**  
![Ekran Görüntüsü - 2022-07-24 03-20-05](https://user-images.githubusercontent.com/50755946/180627202-33cdadce-8a08-4689-a2a4-d09897664679.png)

**Desktop (please complete the following information):**  
 - OS: Fedora Workstation 36 (GNOME)
 - Version [ProtonUp-Qt 2.6.5 Flatpak]

**Additional context**  
Problem doesn't occur on Xorg Session

**Terminal output**  
```
flatpak run net.davidotek.pupgui2
ProtonUp-Qt 2.6.5 by DavidoTek. Build Info: DavidoTek Flathub build.
Python 3.9.9 (main, Nov 10 2011, 15:00:00) [GCC 11.3.0], PySide 6.3.1
Platform: Linux-5.18.13-200.fc36.x86_64-x86_64-with-glibc2.33
Loaded ctmod Proton-GE
Loaded ctmod Wine-GE
Loaded ctmod Boxtron
Loaded ctmod Kron4ek Wine-Builds Vanilla
Loaded ctmod Lutris-Wine
Loaded ctmod Luxtorpeda
Loaded ctmod Proton Tkg
Loaded ctmod Roberta
Loaded ctmod DXVK
Loaded ctmod DXVK Async
qt.pysideplugin: Environment variable PYSIDE_DESIGNER_PLUGINS is not set, bailing out.
qt.pysideplugin: No instance of QPyDesignerCustomWidgetCollection was found.
Gamepad error: No gamepad found.
Could not create decoration from factory! Running with no decorations.
```

**Comment by DavidoTek** [comment]
See https://github.com/DavidoTek/ProtonUp-Qt/issues/78

Happens when [org.kde.WaylandDecoration.QGnomePlatform-decoration](https://github.com/flathub/org.kde.WaylandDecoration.QGnomePlatform-decoration) of the same version 6.3 is installed.

I have to see if there is any solution to this problem, for now you options are (1) to ignore it (2) to uninstall org.kde.WaylandDecoration.QGnomePlatform-decoration//6.3 or (3) to use the AppImage version.

**Comment by ulville** [comment]
Oh I only checked the open issues. Weird #78 is marked as closed since it still happens on new installations. Anyway, good to see you're already aware of the problem. I wanted to address the issue if you weren't aware of it because It creates a convenience issue. I can handle it for myself but for someone who is new to Linux it may be confusing

**Comment by DavidoTek** [comment]
Yes, good you brought that up. The issue was fixed for a short time, but since the latest update of a dependency the issue returned.

**Comment by ulibte** [comment]
I think you can solve the problem if you disable wayland flatpak permission

**Comment by DavidoTek** [comment]
> I think you can solve the problem if you disable wayland flatpak permission

That would be a workaround for the problem, but it would disable Wayland for all desktop environments.

I don't think it's that much of a problem as you can close the window with the 'Close' button and move the window by pressing the Super/Windows-Key and dragging it around.

I think the problem is caused by an older build of PySide 6.3.1 on PyPi, either the Flatpak version needs to include a custom build of PySide (there are some problems currently, but as an advantage it would also reduce the overall size of the Flatpak package) or we'll have to wait for the next release on PyPi (probably next month).
